# Generated by Django 5.1.7 on 2025-03-26 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(upload_to='atas/')),
                ('data_reuniao', models.DateField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('assembleia', 'Assembleia Geral'), ('conselho', 'Conselho Deliberativo'), ('diretoria', 'Diretoria'), ('outros', 'Outros')], max_length=50)),
                ('destaque', models.BooleanField(default=False)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ata',
                'verbose_name_plural': 'Atas',
                'ordering': ['-data_reuniao'],
            },
        ),
    ]
