# Generated by Django 5.1.7 on 2025-04-28 16:20
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('atas', '0002_ata_slug'),
    ]

    operations = [
    ]