# Generated by Django 5.1.7 on 2025-03-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
    ]
