# Generated by Django 5.1.7 on 2025-03-26 16:31

from django.db import migrations

def criar_categoria_padrao(apps, schema_editor):
    Categoria = apps.get_model('sistema_tickets', 'Categoria')
    Categoria.objects.create(
        nome='Geral',
        slug='geral',
        descricao='Categoria padrão para tickets'
    )

def reverter_categoria_padrao(apps, schema_editor):
    Categoria = apps.get_model('sistema_tickets', 'Categoria')
    Categoria.objects.filter(slug='geral').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sistema_tickets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_categoria_padrao, reverter_categoria_padrao),
    ]
