# Generated by Django 5.1.7 on 2025-03-26 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ticket_comentario', 'Novo comentário em ticket'), ('ticket_status', 'Status do ticket atualizado'), ('blog_post', 'Novo post no blog'), ('blog_comentario', 'Novo comentário no blog'), ('ata_nova', 'Nova ata publicada'), ('servico_novo', 'Novo serviço cadastrado')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
